name: PayRespects
version: '${project.version}'
main: space.sanc.payrespects.PayRespectsPlugin
api-version: 1.19
authors: [ Sancires, SiarhiejBahdaniec ]
description: Type /f to pay respects. Translated into Belarusian.
commands:
  f:
    description: Напішыце /f, каб аддаць чэсць.
    usage: /f
    default: true
    permission: payrespects.f